# Generated by Django 5.0.6 on 2024-09-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_image/"),
        ),
    ]
