# Generated by Django 5.0.6 on 2024-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_consumer_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
