name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      # Clear any previously cached SSH keys in the GitHub runner
      - name: Clear SSH Agent Keys
        run: ssh-add -D || true  # This ensures no cached key is carried over from previous jobs

      # Set up SSH with the deploy key from GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # Verify that the SSH key is loaded correctly
      - name: Verify SSH Agent Keys
        run: |
          ssh-add -l

      - name: Deploy to Server
        env:
          SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
          SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
            # Navigate to the project directory
            cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project
            
            # Pull the latest code from the main branch
            git pull origin main
            
            # (Optional) Install any new dependencies
            pip install -r requirements.txt

            # (Optional) Run database migrations for Django projects
            python manage.py migrate --noinput
            
            # (Optional) Collect static files for Django projects
            python manage.py collectstatic --noinput

            # Restart the project service to apply updates
            sudo supervisorctl restart prosffer_project
          EOF
