name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Add SSH Key
      env:
        SSH_KEY_CO_GIT: ${{ secrets.SSH_KEY_CO_GIT}}
      run: |
        # Create the SSH directory and write the private key to it
        mkdir -p ~/.ssh
        echo "$SSH_KEY_CO_GIT" > ~/.ssh/github_prosffer_key
        chmod 600 ~/.ssh/github_prosffer_key
        
        # Start SSH agent and add the SSH key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/github_prosffer_key
        
        # Verify the key is added
        ssh-add -l

    - name: Deploy to Server
      env:
        SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
      run: |
        # Connect to the server and run deployment steps
        ssh -o StrictHostKeyChecking=no $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
          # Configure Git to use this SSH key explicitly in each Git command
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/github_prosffer_key -o StrictHostKeyChecking=no"

          # Navigate to the project directory
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project || exit 1

          # Fetch and pull the latest changes
          $GIT_SSH_COMMAND git fetch origin
          $GIT_SSH_COMMAND git checkout main
          $GIT_SSH_COMMAND git pull origin main

          # Activate virtual environment and install requirements
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 

          # Restart the application
          sudo supervisorctl restart prosffer_project
        EOF
