name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Clear SSH Agent Keys
        run: ssh-add -D || true

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
          SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
            # Navigate to the project directory
            cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project
            
            # Set GIT_SSH_COMMAND for git pull to use the correct SSH key
            GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" git pull origin main
            
            # (Optional) Install any new dependencies
            make prod-install

            # Restart the project service to apply updates
            sudo supervisorctl restart prosffer_project
          EOF
