name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Server
      env:
        SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
      run: |
        # Connect to the server and run deployment steps
        ssh -o StrictHostKeyChecking=no $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
          # Ensure the SSH key is available and permissions are set
          chmod 600 ~/.ssh/github_prosffer_key

          # Configure Git to use this SSH key for GitHub
          git config --global core.sshCommand "ssh -i ~/.ssh/github_prosffer_key -o StrictHostKeyChecking=no"

          # Navigate to the project directory
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project || exit 1

          # Fetch and pull the latest changes
          git fetch origin
          git checkout main
          git pull origin main

          # Activate virtual environment and install requirements
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 

          # Restart the application
          sudo supervisorctl restart prosffer_project
        EOF
