name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Add SSH Key
      env:
        SSH_KEY_CO_GIT: ${{ secrets.SSH_KEY_CO_GIT }}
      run: |
        # Create the SSH directory and set up the SSH key
        mkdir -p ~/.ssh
        echo "$SSH_KEY_CO_GIT" > ~/.ssh/github_prosffer_key
        chmod 600 ~/.ssh/github_prosffer_key
        
        # Configure SSH to use this key for GitHub
        echo "Host github.com\n\tIdentityFile ~/.ssh/github_prosffer_key\n\tStrictHostKeyChecking no" >> ~/.ssh/config

    - name: Deploy to Server
      env:
        SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
      run: |
        # Connect to the server and execute the deployment commands
        ssh -v -o StrictHostKeyChecking=no $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
          # Set up the custom SSH command for Git
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/github_prosffer_key -o StrictHostKeyChecking=no"

          # Navigate to the project directory
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project || exit 1

          # Fetch and pull the latest changes from Git
          $GIT_SSH_COMMAND git fetch origin
          $GIT_SSH_COMMAND git checkout main
          $GIT_SSH_COMMAND git pull origin main

          # Activate virtual environment and install requirements
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 

          # Restart the application
          sudo supervisorctl restart prosffer_project
        EOF
