name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Server
      env:
        SSH_KEY_CO_GIT: ${{ secrets.SSH_KEY_CO_GIT }}
        SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
      run: |
        # Ensure .ssh directory and permissions
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Decode the SSH key
        echo "$SSH_KEY_CO_GIT" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Start the SSH agent and add the GitHub SSH key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

        # Connect to the server and run deployment steps
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
          # Ensure .ssh directory on server and set permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cp ~/.ssh/id_rsa ~/.ssh/id_rsa_remote
          chmod 600 ~/.ssh/id_rsa_remote

          # Git configuration to use SSH key for GitHub
          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa_remote -o StrictHostKeyChecking=no"

          # Navigate to project and update repository
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project || exit 1
          git fetch origin
          git checkout main
          git pull origin main

          # Activate virtual environment and install requirements
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 

          # Restart the application
          sudo supervisorctl restart prosffer_project
        EOF
