name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Server
      env:
        SSH_KEY_CO_GIT: ${{ secrets.SSH_KEY_CO_GIT }}
        SERVER_HOST_CO: ${{ secrets.SERVER_HOST_CO }}
        SERVER_USER_CO: ${{ secrets.SERVER_USER_CO }}
      run: |
        # Save the SSH key for GitHub
        echo "$SSH_KEY_CO_GIT" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key

        # Start the SSH agent and add the GitHub SSH key
        eval "$(ssh-agent -s)"
        ssh-add /tmp/deploy_key

        # Connect to the server and run the deployment steps
        ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key $SERVER_USER_CO@$SERVER_HOST_CO << 'EOF'
          # Set up SSH configuration for GitHub
          mkdir -p ~/.ssh
          echo "Host github.com
            Hostname github.com
            IdentityFile /tmp/deploy_key
            StrictHostKeyChecking no
          " > ~/.ssh/config

          # Navigate to the project directory
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project
          
          # Reset any local changes and pull the latest changes
          git reset --hard
          git pull origin main
          
          # Verify repository state
          git status
          git log -1
          
          # Activate virtual environment and install requirements
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 
          
          # Restart the application
          sudo supervisorctl restart prosffer_project
        EOF
