name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Server
      env:
        SSH_KEY_CO_GIT: ${{ secrets.SSH_KEY_CO_GIT }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        # Save the SSH key for GitHub
        echo "$SSH_KEY_CO_GIT" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key

        # Start the SSH agent and add the GitHub SSH key
        eval "$(ssh-agent -s)"
        ssh-add /tmp/deploy_key

        # Verify SSH connection to GitHub
        ssh -T git@github.com || exit 1

        # Connect to the server and run the deployment steps
        ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project
          git pull git@github.com:geekpnx/prosffer_project.git main
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 
          sudo supervisorctl restart prosffer_project
        EOF
