name: Deploy Prosffer Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Deploy to Server
        env:
          SSH_KEY_CO_GIT: ${{ secrets.SSH_KEY_CO_GIT }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "${SSH_KEY_CO_GIT}" > ssh_key && chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project 
          eval '$(ssh-agent -s)' 
          ssh-add ssh_key
          git pull git@github.com:geekpnx/prosffer_project.git main 
          source /home/ubuntu/Documents/Programming/Projects/FINAL_PROJ/Projects/prosffer_project/.venv/bin/activate 
          make prod-install 
          sudo supervisorctl restart prosffer_project
          EOF
